# Generated by Django 2.1.7 on 2020-11-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleForm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userInfo',
            new_name='FormInfo',
        ),
    ]
