# Generated by Django 2.1.7 on 2020-11-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleForm', '0002_auto_20201129_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormInfo',
            new_name='userInfo',
        ),
    ]
